# Site settings
title: Tianyi Chen
email: ctony@bu.edu
description: Academic webpage of Tianyi Chen
baseurl: ""
url: ""


# Footer info
affiliation: >
    Tianyi Chen<br/>
    PhD Candidate<br/>
    <a href="https://www.bu.edu/cs/research/" target="_blank">Computer Science</a><br/>
    Boston University

location: >
  Room 105A <br/>
  111 Cummington Mall<br/>
  Boston, MA, 02134

contact: >
    <a href="mailto:ctony@bu.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Tianyi via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
# - name: talks
# - name: research
# - name: software
# - name: team
# - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Chen
  first_name: [Tianyi]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
